# Generated by Django 3.2.5 on 2021-07-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.BigIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='classRoom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom'),
        ),
    ]
