# Generated by Django 3.2.5 on 2021-07-26 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('attendence_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='classRoom',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_numeric', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dormitory',
            fields=[
                ('dormitory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_room', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_code', models.CharField(default=None, max_length=100)),
                ('roll', models.BigIntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_title', models.CharField(blank=True, max_length=100, null=True)),
                ('notice', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[(1, 'Yes'), (0, 'No')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period', models.CharField(max_length=20)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
                ('class_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='SessionYear',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('running_year', models.DateField(default=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_color', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=20)),
                ('running_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.sessionyear')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_code', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, max_length=8, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('roll', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('class_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_marks', models.FloatField(default=None)),
                ('obtained_marks', models.FloatField(default=None)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('classRoom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
                ('session', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='mainapp.sessionyear')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('religion', models.CharField(blank=True, max_length=30, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='transport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(blank=True, max_length=500, null=True)),
                ('number_of_vehicle', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('route_fare', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Manager'), (2, 'Teachers'), (3, 'Students'), (4, 'Parent')], default=1, max_length=20),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='customuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='customuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='dormitory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.dormitory'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='running_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.settings'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='transport',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.transport'),
        ),
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher'),
        ),
        migrations.AddField(
            model_name='routine',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject'),
        ),
        migrations.AddField(
            model_name='parent',
            name='customuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enroll',
            name='running_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.settings'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.section'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher'),
        ),
    ]
