# Generated by Django 3.2.5 on 2021-07-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.BigIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='section',
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('classRoom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_marks', models.FloatField(default=0)),
                ('obtained_marks', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='classRoom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom'),
        ),
    ]
