# Generated by Django 3.2.5 on 2021-07-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210723_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('enroll_code', models.CharField(blank=True, max_length=100, null=True)),
                ('roll', models.BigIntegerField(blank=True, null=True)),
                ('class_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
                ('section_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.section')),
                ('student_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
    ]
