# Generated by Django 3.2.5 on 2021-07-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210723_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
