# Generated by Django 3.2.5 on 2021-07-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210726_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='examDateYear',
            new_name='examDate',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='id',
            new_name='exam_id',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='sessionYear',
            new_name='session_year',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_end',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_start',
        ),
        migrations.AddField(
            model_name='exam',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='examName',
            field=models.CharField(max_length=50),
        ),
    ]
