# Generated by Django 3.2.5 on 2021-07-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210719_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('subject', models.CharField(max_length=20)),
                ('period', models.IntegerField()),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
            ],
        ),
    ]
