# Generated by Django 3.2.5 on 2021-07-25 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210725_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='transport',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.transport'),
        ),
    ]
