# Generated by Django 3.2.5 on 2021-07-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_student_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='transport',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.transport'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('examName', models.CharField(max_length=20)),
                ('examDateYear', models.DateField()),
                ('exam_start', models.TimeField()),
                ('exam_end', models.TimeField()),
                ('sessionYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear')),
            ],
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.exam'),
            preserve_default=False,
        ),
    ]
