# Generated by Django 3.2.5 on 2021-07-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210723_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='section',
        ),
    ]
