# Generated by Django 3.2.5 on 2021-07-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_student_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='student',
            name='running_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AddField(
            model_name='student',
            name='enroll',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.enroll'),
        ),
    ]
