# Generated by Django 3.2.5 on 2021-07-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classRoom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
