# Generated by Django 3.2.5 on 2021-07-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_classroom_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('standard', 'section')},
        ),
    ]
