# Generated by Django 3.2.5 on 2021-07-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_students_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='class_room',
            new_name='classRoom',
        ),
    ]
