# Generated by Django 3.2.5 on 2021-07-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_student_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='transport',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.transport'),
        ),
    ]
