# Generated by Django 3.2.5 on 2021-07-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210726_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_points', models.CharField(blank=True, max_length=20, null=True)),
                ('mark_from', models.BigIntegerField(blank=True, null=True)),
                ('mark_upto', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_obtained', models.BigIntegerField(blank=True, null=True)),
                ('mark_total', models.BigIntegerField(blank=True, null=True)),
                ('class_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
                ('comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear')),
                ('exam', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.exam')),
                ('section', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.section')),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
                ('subject', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject')),
            ],
        ),
    ]
