# Generated by Django 3.2.5 on 2021-07-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_classroom_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_code',
            new_name='admission_no',
        ),
    ]
