# Generated by Django 3.2.5 on 2021-07-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210711_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='name',
        ),
    ]
