# Generated by Django 3.2.5 on 2021-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_student_code_student_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='number_of_room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
