# Generated by Django 3.2.5 on 2021-07-23 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_student_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classRoom',
        ),
        migrations.AddField(
            model_name='student',
            name='class_Room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom'),
        ),
    ]
