# Generated by Django 3.2.5 on 2021-07-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='classRoom',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
