# Generated by Django 3.2.5 on 2021-07-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210723_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dormitory_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.dormitory'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='transport_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.transport'),
        ),
    ]
