# Generated by Django 3.2.5 on 2021-07-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210726_2211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('class_id', 'section_id')},
        ),
    ]
