# Generated by Django 3.2.5 on 2021-07-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210726_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='running_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear'),
        ),
    ]
