# Generated by Django 3.2.5 on 2021-07-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210724_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_Room',
            new_name='class_id',
        ),
        migrations.AddField(
            model_name='student',
            name='section_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.section'),
        ),
    ]
