# Generated by Django 3.2.5 on 2021-07-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210721_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='classRoom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.students'),
        ),
    ]
