# Generated by Django 3.2.5 on 2021-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210723_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='route_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
