# Generated by Django 3.2.5 on 2021-07-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210721_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Teachers', 'Teachers'), ('Students', 'Students')], default=1, max_length=10),
        ),
    ]
