# Generated by Django 3.2.5 on 2021-07-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_section_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('class_id', 'name')},
        ),
    ]
