# Generated by Django 3.2.5 on 2021-07-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_students_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='admin',
            new_name='customuser',
        ),
        migrations.RemoveField(
            model_name='students',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='students',
            name='classRoom',
        ),
        migrations.RemoveField(
            model_name='students',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='students',
            name='fatherName',
        ),
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='students',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='students',
            name='motherName',
        ),
        migrations.RemoveField(
            model_name='students',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='students',
            name='parmanent_address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='students',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='students',
            name='updated_at',
        ),
    ]
