# Generated by Django 3.2.5 on 2021-07-23 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210724_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enroll',
            name='year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
