# Generated by Django 3.2.5 on 2021-07-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_enroll_running_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='session',
        ),
        migrations.AddField(
            model_name='subject',
            name='session_year',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='mainapp.settings'),
        ),
    ]
