# Generated by Django 3.2.5 on 2021-07-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_studentappearedexam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='student_id',
            new_name='student',
        ),
    ]
