# Generated by Django 3.2.5 on 2021-07-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_routine_section'),
        ('mainapp', '0007_auto_20210724_0322'),
    ]

    operations = [
    ]
