# Generated by Django 3.2.5 on 2021-07-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210723_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
                ('class_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
                ('teacher_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher')),
            ],
        ),
    ]
