# Generated by Django 3.2.5 on 2021-07-27 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeanceBackUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('year', models.CharField(max_length=30)),
                ('attendance_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.attendance')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.section')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
    ]
