# Generated by Django 3.2.5 on 2021-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_section_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name_numeric',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
