# Generated by Django 3.2.5 on 2022-01-18 20:07

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_auto_20220118_2144'),
        ('mainapp', '0008_academiccalender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-published_at'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='date',
        ),
        migrations.AddField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='pdf_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.file'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], max_length=15, null=True),
        ),
    ]
