# Generated by Django 3.2.5 on 2021-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_student_id_studentattendance_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense_category',
            fields=[
                ('expense_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
    ]
