# Generated by Django 3.2.5 on 2021-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210713_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Principal',
            new_name='Manager',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Manager'), (2, 'Teachers'), (3, 'Students')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
