# Generated by Django 3.2.5 on 2021-07-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_subject_session_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='session_year',
        ),
    ]
