# Generated by Django 3.2.5 on 2021-07-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_attendeancebackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('attendence_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[(1, 'Present'), (0, 'Absent')], max_length=10, null=True)),
                ('student_name', models.CharField(blank=True, max_length=30, null=True)),
                ('rollNo', models.IntegerField()),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.section')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('attendence_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, choices=[(1, 'Present'), (0, 'Absent')], max_length=10, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=30, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.section')),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='attendeancebackup',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendeancebackup',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='attendeancebackup',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='attendeancebackup',
            name='session',
        ),
        migrations.RemoveField(
            model_name='attendeancebackup',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendeanceBackUp',
        ),
    ]
