# Generated by Django 3.2.5 on 2021-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
