# Generated by Django 3.2.5 on 2021-07-28 13:50

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210728_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('class_routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', mainapp.models.DayWeekField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroom')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.section')),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
