# Generated by Django 3.2.5 on 2021-07-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('amount_paid', models.BigIntegerField()),
                ('due', models.BigIntegerField()),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_timestamp', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_details', models.TextField()),
                ('status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], max_length=100)),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('payment_type', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[(1, 'Cash'), (2, 'Cheque'), (3, 'Online')], max_length=100)),
                ('description', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.expense_category')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.invoice')),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
    ]
