# Generated by Django 3.2.5 on 2022-01-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_student_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='customuser',
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.parent'),
        ),
    ]
