# Generated by Django 3.2.5 on 2021-07-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210715_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='rollNo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='classRoom',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
