# Generated by Django 3.2.5 on 2021-07-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_invoice_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_timestamp',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='creation_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[(1, 'Cash'), (2, 'Cheque'), (3, 'Online')], max_length=100),
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
