# Generated by Django 3.2.5 on 2021-07-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210728_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='studentattendance',
            old_name='year',
            new_name='session_year',
        ),
        migrations.RenameField(
            model_name='teacherattendance',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='teacherattendance',
            old_name='year',
            new_name='session_year',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='rollNo',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='class_routine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.classroutine'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher'),
        ),
    ]
