# Generated by Django 3.2.5 on 2021-07-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_subject_session_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='session_year',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear'),
        ),
    ]
