# Generated by Django 3.2.5 on 2021-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210715_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='middleName',
        ),
        migrations.AddField(
            model_name='customuser',
            name='middleName',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
