# Generated by Django 3.2.5 on 2021-07-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210731_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('payment_type', models.CharField(default='Income', max_length=100)),
                ('method', models.CharField(choices=[(1, 'Cash'), (2, 'Cheque'), (3, 'Online')], max_length=100)),
                ('amount', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.invoice')),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
        ),
    ]
