# Generated by Django 3.2.5 on 2021-07-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210728_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='session_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='session_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear'),
        ),
    ]
