# Generated by Django 3.2.5 on 2021-07-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210715_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media/', verbose_name='Image'),
        ),
    ]
