# Generated by Django 3.2.5 on 2021-07-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.expense_category'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
