# Generated by Django 3.2.5 on 2021-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_students_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media/', verbose_name='Image')),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
