# Generated by Django 3.2.5 on 2022-01-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20220122_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='pin_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
