# Generated by Django 3.2.5 on 2021-07-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210730_2136'),
        ('mainapp', '0013_auto_20210731_0053'),
    ]

    operations = [
    ]
