# Generated by Django 3.2.5 on 2022-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_addressbook_pin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='profession',
            new_name='father_profession',
        ),
        migrations.AddField(
            model_name='parent',
            name='family_anuual_income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
