# Generated by Django 3.2.5 on 2022-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20220122_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='house_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
