# Generated by Django 3.2.5 on 2022-01-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_addressbook_house_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='mainapp.subjactList'),
        ),
    ]
