# Generated by Django 3.2.5 on 2021-07-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210716_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='desc',
        ),
    ]
