# Generated by Django 3.2.5 on 2021-07-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_remove_profileimage_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='desc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile/', verbose_name='Image'),
        ),
    ]
