# Generated by Django 3.2.5 on 2022-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20220126_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], default=1, max_length=20),
        ),
    ]
