# Generated by Django 3.2.5 on 2021-07-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20210716_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='student_profile/', verbose_name='Image'),
        ),
    ]
