# Generated by Django 3.2.5 on 2021-07-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('online', 'online')], max_length=100, null=True),
        ),
    ]
