# Generated by Django 3.2.5 on 2021-08-01 19:46

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='day',
            field=mainapp.models.DayWeekField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'cash'), ('cheque', 'cheque'), ('online', 'online')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default='Income', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sessionyear'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
