# Generated by Django 3.2.5 on 2021-08-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20210802_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_category',
            fields=[
                ('invoice_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.invoice_category'),
        ),
    ]
