# Generated by Django 3.2.5 on 2021-08-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210807_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='category',
        ),
    ]
