# Generated by Django 3.2.5 on 2021-08-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_invoice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_from_inv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
