# Generated by Django 3.2.5 on 2021-08-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_payment_due_from_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='creation_timestamp',
            field=models.DateField(),
        ),
    ]
